version: '3'
services:
  api:
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports: 
        - '8080:8080'
    tty: true
    volumes:
      - ./src:/app
    command: 'flask run -h 0.0.0.0 -p 8080'