version: '3'
services:
  api:
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports: 
        - '3000:3000'
    tty: true
    volumes:
      - ./src:/app
    command: 'flask run -h 0.0.0.0 -p 3000'