version: 2.1
jobs:
    # build:
    #     machine: true
    #     steps:
    #         - checkout
    #         - run:
    #             name: docker-compose build
    #             command: docker-compose build
    test:
        docker: 
            - image: circleci/python:3.8.2
        steps:
            - checkout
            - run:
                name: unit test
                command: python3 src/__colorPicker.test.py