version: 2.1
jobs:
    build:
        machine: true
        steps:
            - checkout
            - run:
                name: docker-compose build
                command: docker-compose build
            - run:
                name: unit test
                command: docker-compose up test
    deploy:
        machine: true
        steps: 
            - checkout
            - run:
                name: login
                command: docker login --username=$HEROKU_USER_NAME --password=$HEROKU_API_KEY registry.heroku.com
            - run:
                name: heorku setup
                command: |
                    chmod +x .circleci/setup-heroku.sh
                    .circleci/setup-heroku.sh
            - run: 
                name: deploy heroku
                command: |
                    heroku container:push --app ${HEROKU_APP_NAME} web
                    heroku container:release --app ${HEROKU_APP_NAME} web

workflows:
    version: 2
    test:
        jobs:
            - build
            - deploy:
                requires:
                    - build