version: 2.1
jobs:
    build:
        machine: true
        steps:
            - checkout
            - run:
                name: docker-compose build
                command: docker-compose build
            - run: 
                name: docker-compose up
                command: docker-compose up
    test:
        docker: 
            - image: circleci/python:3.8.2
        steps:
            - checkout
            - run:
                name: unit test
                command: python3 src/__colorPicker.test.py

workflows:
    version: 2
    test:
        jobs:
            - build
            - test