version: 2.1
jobs:
    build:
        machine: true
        steps:
            - checkout
            - run:
                name: docker-compose build
                command: docker-compose build
            - run: 
                name: docker-compose up
                command: docker-compose up development
            - run:
                name: unit test
                command: docker-compose up test

workflows:
    version: 2
    test:
        jobs:
            - build